require 'data_structures/stack'
require 'data_structures/queue'
require 'data_structures/linked_list'
require 'data_structures/binary_tree'
require 'data_structures/lru_cache'
require 'data_structures/heap'
